name: Go

on:
  push:
    paths:
      - "/main.go"
      - "/go.mod"
      - "/.github/**"
  pull_request:
    branches: [ "master" ]

jobs:

  build-ubn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build

    - uses: actions/upload-artifact@v4
      with:
        name: cfget-ubn
        path: ./cfget

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build

    - uses: actions/upload-artifact@v4
      with:
        name: cfget-mac
        path: ./cfget
